### ISSUE TITLE
关于支持sgx的版本

### ISSUE THREAD

**Issue by Grace-byte912** [ziqi-zhang/TAOISM#1]
这个框架是只能在支持sgx2的环境下运行吗

**Comment by linzechaochao** [comment]
> 这个框架是只能在支持sgx2的环境下运行吗

请问你 make 成功了吗？
我出现如下错误：
Fatal error: can't create SGXDNN/bin_sgx/sgxaes_asm.o: No such file or directory
make: *** [Makefile:245: SGXDNN/bin_sgx/sgxaes_asm.o] Error 1

![sgx](https://github.com/ziqi-zhang/TAOISM/assets/49217552/4f2be762-3806-4033-8436-55811acf96e4)

**Comment by linzechaochao** [comment]
> 这个框架是只能在支持sgx2的环境下运行吗

请问你 make 成功了吗？
我出现如下错误：
Fatal error: can't create SGXDNN/bin_sgx/sgxaes_asm.o: No such file or directory
make: *** [Makefile:245: SGXDNN/bin_sgx/sgxaes_asm.o] Error 1
![Uploading sgx.png…]()

**Comment by linzechaochao** [comment]
> 这个框架是只能在支持sgx2的环境下运行吗

请问你 make 成功了吗？
我出现如下错误：
Fatal error: can't create SGXDNN/bin_sgx/sgxaes_asm.o: No such file or directory
make: *** [Makefile:245: SGXDNN/bin_sgx/sgxaes_asm.o] Error 1
![sgx](https://github.com/ziqi-zhang/TAOISM/assets/49217552/efd9c257-7801-4dce-9cf9-440c12c76537)

**Comment by ziqi-zhang** [comment]
这个应该是没有 `SGXDNN/bin_sgx` 的目录，你可以试着手动创建一下这个目录然后再make一下试试？

**Comment by linzechaochao** [comment]
> 这个应该是没有 `SGXDNN/bin_sgx` 的目录，你可以试着手动创建一下这个目录然后再make一下试试？
谢谢，照你说的创建SGXDNN/bin_sgx 的目录后重新make之后出错了以下错误，这是怎么回事呢？麻烦看一下
./Include/randpool_common.hpp:57:10: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory
   57 | #include <unsupported/Eigen/CXX11/Tensor>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:207: App/bin/randpool_common.o] Error 1
![sgx](https://github.com/ziqi-zhang/TAOISM/assets/49217552/c7e7b9a8-f281-40ca-bb46-34550da97a68)

**Comment by ziqi-zhang** [comment]
I pushed a new version with the dependency directories. You can try the new one?

**Comment by linzechaochao** [comment]
> I pushed a new version with the dependency directories. You can try the new one?

ok ,I try th new one, but occur the error as follow:
/usr/bin/ld: warning: App/bin/crypto_common.o, needed by App/bin/enclave_bridge.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: App/bin/enclave_bridge.so: undefined reference to `decrypt(unsigned char const*, unsigned int, unsigned char*, unsigned char (*) [    12], unsigned char (*) [16], unsigned char*)'
/usr/bin/ld: App/bin/enclave_bridge.so: undefined reference to `encrypt(unsigned char*, unsigned int, unsigned char*, unsigned char (*) [12], u    nsigned char (*) [16])'
collect2: error: ld returned 1 exit status
make: *** [Makefile:227: taoism_app] Error 1
![sgx](https://github.com/ziqi-zhang/TAOISM/assets/49217552/068a5f39-2804-4747-ba62-f9130c492d01)

**Comment by ziqi-zhang** [comment]
Can you rerun `make clean` and remake, and paste the full log? It seems that App/bin/crypto_common.o, which is included [here](https://github.com/ziqi-zhang/TAOISM/blob/5336cec9912613981d28d851c2247bc750bc1ca5/Makefile#L214) in the Makefile, didn't compile.

**Comment by linzechaochao** [comment]
> Can you rerun `make clean` and remake, and paste the full log? It seems that App/bin/crypto_common.o, which is included [here](https://github.com/ziqi-zhang/TAOISM/blob/5336cec9912613981d28d851c2247bc750bc1ca5/Makefile#L214) in the Makefile, didn't compile.

OK，the full log as the follow:
![sgx](https://github.com/ziqi-zhang/TAOISM/assets/49217552/9242ddaa-ed9a-47bd-9ed5-497c946f5abb)
You can check where the error is，thank you so much!

**Comment by ziqi-zhang** [comment]
I tried to clone the new code version and it can compile in my machine. 

It looks that your problem is `App/bin/crypto_common.o` is not successfully built, which is specified in the Makefile of [here](https://github.com/ziqi-zhang/TAOISM/blob/5336cec9912613981d28d851c2247bc750bc1ca5/Makefile#L214). I think you can try following things to diagnos:
- Can you check if `App/bin/crypto_common.o` exists? 
- Try to manually compile `App/bin/crypto_common.o` using the command [here](https://github.com/ziqi-zhang/TAOISM/blob/5336cec9912613981d28d851c2247bc750bc1ca5/Makefile#L214) (remember to substitute the variables `CXX`, `App_Cpp_Flags_WithoutSGX`, and `App_Link_Flags` of the makefile). Then see if `App/bin/crypto_common.o` is successfully compiled.

I attached the brief log of my compilation here:
```
GEN  =>  App/Enclave_u.c  current---------------dir
CC   <=  App/Enclave_u.c
CXX  <=  App/aes_stream_common.cpp
CC   <=  SGXDNN/sgxaes_asm.S
CXX  <=  App/sgxaes_common.cpp
CXX  <=  App/crypto_common.cpp
CXX  <=  App/randpool_common.cpp
CXX  <=  App/common_utils.cpp
CXX  <=  App/enclave_bridge.cpp
LINK =>  taoism_app
GEN  =>  Enclave/Enclave_t.c
CC   <=  Enclave/Enclave_t.c
CXX  <=  Enclave/Enclave.cpp
CXX  <=  Enclave/sgxdnn.cpp
CXX  <=  SGXDNN/sgxdnn_main.cpp
CXX  <=  SGXDNN/chunk_manager.cpp
CXX  <=  SGXDNN/secret_tensor.cpp
CXX  <=  SGXDNN/xoshiro.cpp
CXX  <=  SGXDNN/stochastic.cpp
CXX  <=  SGXDNN/Crypto.cpp
CXX  <=  SGXDNN/sgxaes.cpp
CXX  <=  SGXDNN/aes-stream.cpp
CXX  <=  SGXDNN/utils.cpp
BEFORE LINK =--------------------------------->  enclave.so

LINK =>  enclave.so
<!-- Please refer to User's Guide for the explanation of each field -->
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <!--  <StackMaxSize>0x20000000</StackMaxSize>-->
    <StackMaxSize>0x2000000</StackMaxSize>
    <!--  <HeapMaxSize>0x99000000</HeapMaxSize>-->
    <!--  <HeapMaxSize>0x280000000</HeapMaxSize> -->
    <HeapMaxSize>0x8000000</HeapMaxSize>
    <!--  <HeapMaxSize>0x8000000</HeapMaxSize>-->
    <TCSNum>4</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
tcs_num 4, tcs_max_num 4, tcs_min_pool 1
The required memory is 268914688B.
The required memory is 0x10075000, 262612 KB.
Succeed.
SIGN =>  enclave.signed.so
The project has been built in pre-release hardware mode.
```

**Comment by ziqi-zhang** [comment]
@Grace-byte912 抱歉之前忘了回复你那个问题了。这个框架是基于SGX SDK开发的，所以只要SDK支持的应该都可以支持。我的实验是在 128MB 内存的SGX硬件上跑的。你这里说的SGX2 我猜应该是512G那种，我觉得只要SDK能运行的话这个框架应该就能跑。

**Comment by linzechaochao** [comment]
> I tried to clone the new code version and it can compile in my machine.
> 
> It looks that your problem is `App/bin/crypto_common.o` is not successfully built, which is specified in the Makefile of [here](https://github.com/ziqi-zhang/TAOISM/blob/5336cec9912613981d28d851c2247bc750bc1ca5/Makefile#L214). I think you can try following things to diagnos:
> 
> * Can you check if `App/bin/crypto_common.o` exists?
> * Try to manually compile `App/bin/crypto_common.o` using the command [here](https://github.com/ziqi-zhang/TAOISM/blob/5336cec9912613981d28d851c2247bc750bc1ca5/Makefile#L214) (remember to substitute the variables `CXX`, `App_Cpp_Flags_WithoutSGX`, and `App_Link_Flags` of the makefile). Then see if `App/bin/crypto_common.o` is successfully compiled.
> 
> I attached the brief log of my compilation here:
> 
> ```
> GEN  =>  App/Enclave_u.c  current---------------dir
> CC   <=  App/Enclave_u.c
> CXX  <=  App/aes_stream_common.cpp
> CC   <=  SGXDNN/sgxaes_asm.S
> CXX  <=  App/sgxaes_common.cpp
> CXX  <=  App/crypto_common.cpp
> CXX  <=  App/randpool_common.cpp
> CXX  <=  App/common_utils.cpp
> CXX  <=  App/enclave_bridge.cpp
> LINK =>  taoism_app
> GEN  =>  Enclave/Enclave_t.c
> CC   <=  Enclave/Enclave_t.c
> CXX  <=  Enclave/Enclave.cpp
> CXX  <=  Enclave/sgxdnn.cpp
> CXX  <=  SGXDNN/sgxdnn_main.cpp
> CXX  <=  SGXDNN/chunk_manager.cpp
> CXX  <=  SGXDNN/secret_tensor.cpp
> CXX  <=  SGXDNN/xoshiro.cpp
> CXX  <=  SGXDNN/stochastic.cpp
> CXX  <=  SGXDNN/Crypto.cpp
> CXX  <=  SGXDNN/sgxaes.cpp
> CXX  <=  SGXDNN/aes-stream.cpp
> CXX  <=  SGXDNN/utils.cpp
> BEFORE LINK =--------------------------------->  enclave.so
> 
> LINK =>  enclave.so
> 
> <EnclaveConfiguration>
>     <ProdID>0</ProdID>
>     <ISVSVN>0</ISVSVN>
>     
>     <StackMaxSize>0x2000000</StackMaxSize>
>     
>     
>     <HeapMaxSize>0x8000000</HeapMaxSize>
>     
>     <TCSNum>4</TCSNum>
>     <TCSPolicy>1</TCSPolicy>
>     <DisableDebug>0</DisableDebug>
>     <MiscSelect>0</MiscSelect>
>     <MiscMask>0xFFFFFFFF</MiscMask>
> </EnclaveConfiguration>
> tcs_num 4, tcs_max_num 4, tcs_min_pool 1
> The required memory is 268914688B.
> The required memory is 0x10075000, 262612 KB.
> Succeed.
> SIGN =>  enclave.signed.so
> The project has been built in pre-release hardware mode.
> ```

thanks your answer, i found App/bin/crypto_common.o exists after remake(in sim mode), but it also occurs the error as follow:
![sgx](https://github.com/ziqi-zhang/TAOISM/assets/49217552/164e604c-9497-4524-bcae-3bed3bdd41fc)

**Comment by linzechaochao** [comment]
> I tried to clone the new code version and it can compile in my machine.
> 
> It looks that your problem is `App/bin/crypto_common.o` is not successfully built, which is specified in the Makefile of [here](https://github.com/ziqi-zhang/TAOISM/blob/5336cec9912613981d28d851c2247bc750bc1ca5/Makefile#L214). I think you can try following things to diagnos:
> 
> * Can you check if `App/bin/crypto_common.o` exists?
> * Try to manually compile `App/bin/crypto_common.o` using the command [here](https://github.com/ziqi-zhang/TAOISM/blob/5336cec9912613981d28d851c2247bc750bc1ca5/Makefile#L214) (remember to substitute the variables `CXX`, `App_Cpp_Flags_WithoutSGX`, and `App_Link_Flags` of the makefile). Then see if `App/bin/crypto_common.o` is successfully compiled.
> 
> I attached the brief log of my compilation here:
> 
> ```
> GEN  =>  App/Enclave_u.c  current---------------dir
> CC   <=  App/Enclave_u.c
> CXX  <=  App/aes_stream_common.cpp
> CC   <=  SGXDNN/sgxaes_asm.S
> CXX  <=  App/sgxaes_common.cpp
> CXX  <=  App/crypto_common.cpp
> CXX  <=  App/randpool_common.cpp
> CXX  <=  App/common_utils.cpp
> CXX  <=  App/enclave_bridge.cpp
> LINK =>  taoism_app
> GEN  =>  Enclave/Enclave_t.c
> CC   <=  Enclave/Enclave_t.c
> CXX  <=  Enclave/Enclave.cpp
> CXX  <=  Enclave/sgxdnn.cpp
> CXX  <=  SGXDNN/sgxdnn_main.cpp
> CXX  <=  SGXDNN/chunk_manager.cpp
> CXX  <=  SGXDNN/secret_tensor.cpp
> CXX  <=  SGXDNN/xoshiro.cpp
> CXX  <=  SGXDNN/stochastic.cpp
> CXX  <=  SGXDNN/Crypto.cpp
> CXX  <=  SGXDNN/sgxaes.cpp
> CXX  <=  SGXDNN/aes-stream.cpp
> CXX  <=  SGXDNN/utils.cpp
> BEFORE LINK =--------------------------------->  enclave.so
> 
> LINK =>  enclave.so
> 
> <EnclaveConfiguration>
>     <ProdID>0</ProdID>
>     <ISVSVN>0</ISVSVN>
>     
>     <StackMaxSize>0x2000000</StackMaxSize>
>     
>     
>     <HeapMaxSize>0x8000000</HeapMaxSize>
>     
>     <TCSNum>4</TCSNum>
>     <TCSPolicy>1</TCSPolicy>
>     <DisableDebug>0</DisableDebug>
>     <MiscSelect>0</MiscSelect>
>     <MiscMask>0xFFFFFFFF</MiscMask>
> </EnclaveConfiguration>
> tcs_num 4, tcs_max_num 4, tcs_min_pool 1
> The required memory is 268914688B.
> The required memory is 0x10075000, 262612 KB.
> Succeed.
> SIGN =>  enclave.signed.so
> The project has been built in pre-release hardware mode.
> ```

Sorry, I can not find the funtion（decrypt&encrypt） in the whole project dir：
![sgx](https://github.com/ziqi-zhang/TAOISM/assets/49217552/d50a2d9f-67e4-4da6-bd41-3febe9f2c60f)

**Comment by 13784342876x-lab** [comment]
> > 我尝试克隆新代码版本，它在我的机器上可以编译。
> > 看起来你的问题是`App/bin/crypto_common.o`构建没有成功，这在 Makefile 文件中有说明[。](https://github.com/ziqi-zhang/TAOISM/blob/5336cec9912613981d28d851c2247bc750bc1ca5/Makefile#L214)你可以尝试以下方法来诊断问题：
> > 
> > * 你能查一下是否`App/bin/crypto_common.o`存在吗？
> > * 尝试使用[此处的](https://github.com/ziqi-zhang/TAOISM/blob/5336cec9912613981d28d851c2247bc750bc1ca5/Makefile#L214)`App/bin/crypto_common.o`命令手动编译（请记住替换Makefile 中的变量 `<variables>` 、 `<variables> ` 和 `<variables> `）。然后查看是否编译成功。[](https://github.com/ziqi-zhang/TAOISM/blob/5336cec9912613981d28d851c2247bc750bc1ca5/Makefile#L214)`CXX``App_Cpp_Flags_WithoutSGX``App_Link_Flags``App/bin/crypto_common.o`
> > 
> > 我在此附上我的编译日志：
> > ```
> > GEN  =>  App/Enclave_u.c  current---------------dir
> > CC   <=  App/Enclave_u.c
> > CXX  <=  App/aes_stream_common.cpp
> > CC   <=  SGXDNN/sgxaes_asm.S
> > CXX  <=  App/sgxaes_common.cpp
> > CXX  <=  App/crypto_common.cpp
> > CXX  <=  App/randpool_common.cpp
> > CXX  <=  App/common_utils.cpp
> > CXX  <=  App/enclave_bridge.cpp
> > LINK =>  taoism_app
> > GEN  =>  Enclave/Enclave_t.c
> > CC   <=  Enclave/Enclave_t.c
> > CXX  <=  Enclave/Enclave.cpp
> > CXX  <=  Enclave/sgxdnn.cpp
> > CXX  <=  SGXDNN/sgxdnn_main.cpp
> > CXX  <=  SGXDNN/chunk_manager.cpp
> > CXX  <=  SGXDNN/secret_tensor.cpp
> > CXX  <=  SGXDNN/xoshiro.cpp
> > CXX  <=  SGXDNN/stochastic.cpp
> > CXX  <=  SGXDNN/Crypto.cpp
> > CXX  <=  SGXDNN/sgxaes.cpp
> > CXX  <=  SGXDNN/aes-stream.cpp
> > CXX  <=  SGXDNN/utils.cpp
> > BEFORE LINK =--------------------------------->  enclave.so
> > 
> > LINK =>  enclave.so
> > 
> > <EnclaveConfiguration>
> >     <ProdID>0</ProdID>
> >     <ISVSVN>0</ISVSVN>
> >     
> >     <StackMaxSize>0x2000000</StackMaxSize>
> >     
> >     
> >     <HeapMaxSize>0x8000000</HeapMaxSize>
> >     
> >     <TCSNum>4</TCSNum>
> >     <TCSPolicy>1</TCSPolicy>
> >     <DisableDebug>0</DisableDebug>
> >     <MiscSelect>0</MiscSelect>
> >     <MiscMask>0xFFFFFFFF</MiscMask>
> > </EnclaveConfiguration>
> > tcs_num 4, tcs_max_num 4, tcs_min_pool 1
> > The required memory is 268914688B.
> > The required memory is 0x10075000, 262612 KB.
> > Succeed.
> > SIGN =>  enclave.signed.so
> > The project has been built in pre-release hardware mode.
> > ```
> 
> 抱歉，我在整个项目目录中都找不到（解密和加密）函数： ![sgx](https://github.com/ziqi-zhang/TAOISM/assets/49217552/d50a2d9f-67e4-4da6-bd41-3febe9f2c60f)

我也是，请问您解决了吗
